# Generated by Django 5.2.6 on 2025-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fovisste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='record',
            name='folio',
        ),
        migrations.AddField(
            model_name='record',
            name='cadena1',
            field=models.CharField(blank=True, default='', max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='cpto',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='impor',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='lote_actual',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='lote_anterior',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='observacio',
            field=models.CharField(blank=True, default='', max_length=47, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ptje',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='qna',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='qna_ini',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=13, null=True),
        ),
    ]
