# Generated by Django 5.2.6 on 2025-10-07 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fovisste', '0002_remove_record_curp_remove_record_folio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='record',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00', verbose_name='Fecha de Carga'),
        ),
        migrations.AddField(
            model_name='record',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Carga'),
        ),
    ]
