# Generated by Django 5.2.6 on 2025-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fovisste', '0003_auto_20251007_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AlterField(
            model_name='record',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lote_anterior',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
